# Generated by Django 4.0.4 on 2022-05-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['create'],
            },
        ),
    ]
